<a href="https://colab.research.google.com/github/yashagarwal6/data_science-/blob/main/lec5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
#create a 5*5 array of random integers
#find mean of values row and column wise
#replace all even numbers with -1
#sort the array row and column wise
#find the row and column wise sum seperately
#count the number of -ve's in each column

import numpy as np
arr = np.random.randint(1,91,(5,5))
print(arr)

print("\n")
print("row wise mean : ")
print(np.mean(arr,axis=1))

print("\n")
print("column wise mean : ")
print(np.mean(arr,axis=0))

modified_arr = np.where(arr%2==0,-1,arr) #arr[arr % 2 == 0] = -1 this will not create new var
print("\n arr after replace evens with -1 :")
print(modified_arr)
print("\n")

print("row wise sorted arr :")
y = np.sort(arr, axis=1)
print(y)


print("\n")
x = np.sort(arr, axis=0)
print("column wise sorted arr :")
print(x)

print("\n")
print("row wise sum of arr :")
print(np.sum(arr,axis=1))

print("\n")
print("column wise sum of arr :")
print(np.sum(arr,axis=0))

print("\n")
print("number of -1 in each column")
print(np.sum(np.where(modified_arr<0,1,0),axis=0))
# print(np.sum(arr<0,axis=0))




[[33 28 89 14 53]
 [17 34 26 30 37]
 [61 41 67 76 53]
 [75 45 10  2 47]
 [54 56 47 78 54]]


row wise mean : 
[43.4 28.8 59.6 35.8 57.8]


column wise mean : 
[48.  40.8 47.8 40.  48.8]

 arr after replace evens with -1 :
[[33 -1 89 -1 53]
 [17 -1 -1 -1 37]
 [61 41 67 -1 53]
 [75 45 -1 -1 47]
 [-1 -1 47 -1 -1]]


row wise sorted arr :
[[14 28 33 53 89]
 [17 26 30 34 37]
 [41 53 61 67 76]
 [ 2 10 45 47 75]
 [47 54 54 56 78]]


column wise sorted arr :
[[17 28 10  2 37]
 [33 34 26 14 47]
 [54 41 47 30 53]
 [61 45 67 76 53]
 [75 56 89 78 54]]


row wise sum of arr :
[217 144 298 179 289]


column wise sum of arr :
[240 204 239 200 244]


number of -1 in each column
[1 3 2 5 1]


In [25]:
#question 2
#inverntory control system
#task:
#create 5*5 array(stock levels) range - 20 to 80
#create another 5*5 array (demand)
#compute:
#remaining_stock = stock - demand
#replace:
#negative values -> 0 (out of stock)
#find:
#total shotage
#products with zero stocks
#stock each based on remaining stock

import numpy as np
stock = np.random.randint(20,80,(5,5))
demand = np.random.randint(1,90,(5,5))
print('stock levels: ')
print(stock)
print("\n")

print('demand: ')
print(demand)
print("\n")
remaining_stock = stock - demand
print("remaing stock : ")
print(remaining_stock)
print("\n")
print('remaing after replacement:')
remaining_stock = np.where(remaining_stock<0,0,remaining_stock)
print(remaining_stock)

print("\n")
zero_stock=np.sum(np.where(remaining_stock==0,1,0),axis=0)
print("zero stocks:")
print(zero_stock)

stock levels: 
[[54 47 34 74 25]
 [42 26 26 49 66]
 [58 58 23 47 60]
 [69 29 33 28 44]
 [47 40 39 56 29]]


demand: 
[[14 86 41 15 15]
 [49 11 12 17 23]
 [14 70 48 54 21]
 [32 61  5 79 16]
 [51 39 11 78 12]]


remaing stock : 
[[ 40 -39  -7  59  10]
 [ -7  15  14  32  43]
 [ 44 -12 -25  -7  39]
 [ 37 -32  28 -51  28]
 [ -4   1  28 -22  17]]


remaing after replacement:
[[40  0  0 59 10]
 [ 0 15 14 32 43]
 [44  0  0  0 39]
 [37  0 28  0 28]
 [ 0  1 28  0 17]]


zero stocks:
[2 3 2 3 0]
